#!/usr/bin/env bash
set -euo pipefail

version=$(curl -sSL https://raw.githubusercontent.com/cisco-sso/kdk/master/cmd/root.go | grep -e 'kdk.Version' | grep "[0-9]" | sed 's|.*"\(.*\)"|\1|g')

archtype=$(uname -m)
if [[ ${archtype} == 'x86_64' ]]; then
  arch="amd64"
elif [[ ${archtype}  == 'x86_32' ]]; then
  arch="386"
else
  echo "Unsupported architecture"
  exit 1
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  os="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  os="darwin"
elif [[ "$OSTYPE" =~ ^(cygwin|msys)$ ]]; then
  os="windows"
else
  echo "Unsupported OS"
  exit 1
fi

if [[ ${os} =~ ^(linux|darwin)$ ]]; then
  kdk_bin=/tmp/${os}-${arch}/kdk
  kdk_destination=/usr/local/bin/kdk
elif [[ $os == "windows" ]]; then
  kdk_bin=/tmp/${os}-${arch}/kdk.exe
  kdk_destination=/usr/bin/kdk
fi

if [[ ${os} =~ ^(linux|darwin)$ ]]; then
  if [[ $EUID -ne 0 ]]; then
     echo "This script must be run as root" 1>&2
     exit 1
  fi
fi

dist_tgz=kdk-${version}-${os}-${arch}.tar.gz
download_uri=https://github.com/cisco-sso/kdk/releases/download/${version}/${dist_tgz}

curl -sSL ${download_uri} | tar -C /tmp -xz

chmod a+x ${kdk_bin}
mv ${kdk_bin} ${kdk_destination}

rm -fr /tmp/${os}-${arch}
