#!/usr/bin/env bash
set -euo pipefail

version=$(curl -sSL "https://api.github.com/repos/cisco-sso/kdk/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

archtype=$(uname -m)
if [[ ${archtype} == 'x86_64' ]]; then
  arch="amd64"
elif [[ ${archtype}  == 'x86_32' ]]; then
  arch="386"
else
  echo "Unsupported architecture"
  exit 1
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  os="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  os="darwin"
else
  echo "Unsupported Operating System"
  exit 1
fi

tmpdir=/tmp/kdk-${os}-${arch}
kdk_bin=${tmpdir}/kdk
kdk_destination=/usr/local/bin/kdk

dist_tgz=kdk-${version}-${os}-${arch}.tar.gz
download_uri=https://github.com/cisco-sso/kdk/releases/download/${version}/${dist_tgz}

mkdir -p ${tmpdir}
curl -sSL ${download_uri} | tar -xz -C ${tmpdir}

if [[ ! -d /usr/local/bin ]]; then
    # Create the empty parent directory where the kdk binary will live
    #   Echo the command so the user may view what was executed
    (set -x; sudo install -m 0755 -d $(dirname ${kdk_destination}))
fi

# Create the kdk binary executable file
#   Echo the command so the user may view what was executed
(set -x; sudo install -m 0755 -o ${USER} ${kdk_bin} ${kdk_destination})

rm -fr ${tmpdir}
