#!/usr/bin/env bash
set -euo pipefail

OS=$(grep "^ID" /etc/os-release | cut -d= -f2)  # debian | centos
SUDO_GROUP=$([ "$OS" == "debian" ] && echo "sudo" || echo "wheel")

if [ ! -f "/etc/kdk/provisioned" ]; then
    useradd ${KDK_USERNAME} -m -G ${SUDO_GROUP},docker -s ${KDK_SHELL}
    chown ${KDK_USERNAME}:${KDK_USERNAME} /home/${KDK_USERNAME}
    chown -R ${KDK_USERNAME}:${KDK_USERNAME} /home/${KDK_USERNAME}/.ssh
    touch /var/log/kdk-provision.log && \
      chown ${KDK_USERNAME} /var/log/kdk-provision.log && \
      chmod 0600 /var/log/kdk-provision.log

    # Set no password for sudo users
    if [ "$OS" == "debian" ]; then
      sed -i 's@\%sudo\tALL=(ALL:ALL) ALL@\%sudo\tALL=(ALL) NOPASSWD:ALL@g' /etc/sudoers
    else
      sed -i 's@^# %wheel@%wheel@g' /etc/sudoers
    fi

    # Setup yadm dotfiles
    runuser -l ${KDK_USERNAME} -c "yadm clone --bootstrap ${KDK_DOTFILES_REPO}" >> /var/log/kdk-provision.log 2>&1
    mkdir -p /etc/kdk
    echo 1 > /etc/kdk/provisioned
fi

exit 0
